backend/models/Kegiatan.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "kegiatan".
 *
 * @property int $id_kegiatan
 * @property int $id_mhs
 * @property string $jenis_kegiatan
 * @property string $upload_proposal

 *
 * @property Ruangan[] $ruangans
 */
class Kegiatan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kegiatan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_mhs', 'jenis_kegiatan', 'upload_proposal'], 'required'],
            [['id_mhs'], 'integer'],
            [['jenis_kegiatan'], 'string', 'max' => 255],
            [['upload_proposal'],'file','extensions' => 'pdf'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_kegiatan' => 'Id Kegiatan',
            'id_mhs' => 'Id Mhs',
            'jenis_kegiatan' => 'Jenis Kegiatan',
            'upload_proposal' => 'Upload Proposal',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRuangans()
    {
        return $this->hasMany(Ruangan::className(), ['id_kegiatan' => 'id_kegiatan']);
    }
    public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_mhs' => 'id_mhs']);
    }
}

frontend/models/Kegiatan.php
<?php

namespace app\models;

use Yii;


/**
 * This is the model class for table "kegiatan".
 *
 * @property int $id_kegiatan
 * @property string $jenis_kegiatan
 * @property string $upload_proposal
 */
class Kegiatan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kegiatan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['jenis_kegiatan','upload_proposal'], 'required'],
            [['jenis_kegiatan'], 'string', 'max' => 255],
            [['upload_proposal'], 'file','skipOnEmpty'=>TRUE,'extensions'=>'pdf']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_kegiatan' => 'Id Kegiatan',
            'jenis_kegiatan' => 'Jenis Kegiatan',
            'upload_proposal' => 'Proposal Kegiatan',
        ];
    }

    public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }
}

backend/controllers/KegiatanController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Kegiatan;
use backend\models\KegiatanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\LoginForm;
use yii\filters\AccessControl;
use backend\models\Notifikasi;

/**
 * KegiatanController implements the CRUD actions for Kegiatan model.
 */
class KegiatanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules'=> [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Lists all Kegiatan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KegiatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = ['pageSize' => 5];
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionApprove($id)
    {
        $model = Kegiatan::find()->where(['id_kegiatan' => $id])->one();
        $notif = new Notifikasi();
        $notif->id_mhs = $model->id_mhs;
        $notif->desc = "Request Kegiatan Diterima";
        $model->status_request_id=1;
        $searchModel = new KegiatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if($model->save()){
            
           if ($notif->save(false)) {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        
    }
}

public function actionDownload($id) 
{ 
    $download = Kegiatan::findOne($id); 
    $path=Yii::getAlias('@frontend') . '/web/Kegiatan Mahasiswa/' . $download->upload_proposal;
    if (file_exists($path)) {
        return Yii::$app->response->sendFile($path);
    }
}

public function actionExcel()
{
    $searchModel = new KegiatanSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('excel', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
    ]);
}


public function actionReject($id)
{
    $model = Kegiatan::find()->where(['id_kegiatan' => $id])->one();
    $notif = new Notifikasi();
    $notif->id_mhs = $model->id_mhs;
    $notif->desc = "Request Kegiatan Ditolak";
    $model->status_request_id=2;
    $searchModel = new KegiatanSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    if($model->save()){
    //disini buat savenya
       if ($notif->save(false)) {
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
}
}


    public function actionPdf($id) {
    $model = Kegiatan::findOne($id);
        
    

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/Kegiatan Mahasiswa/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_proposal);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

        
}

    /**
     * Displays a single Kegiatan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Kegiatan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model=new Kegiatan;
        if(isset($_POST['NamaModel']))
        {
            $model->attributes=$_POST['Kegiatan'];
            $model->status_request_id=0;
            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }
        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates an existing Kegiatan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdates($id)
    {
        $model=$this->loadModel($id);
        $model->status=1;
        if($model->save())
            $this->redirect(array('view','id'=>$model->id));

        $this->render('update',array(
            'model'=>$model,
        ));
    }


    public function actionPdf($id) {
        $model = Kegiatan::findOne($id);

    // This will need to be the path relative to the root of your app.
        $filePath = '/web/Kegiatan Mahasiswa /';
    // Might need to change '@app' for another alias
        $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_proposal);

        
        return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);


    }


    /**
     * Deletes an existing Kegiatan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    

    /**
     * Finds the Kegiatan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kegiatan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kegiatan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
}

frontend/controllers/KegiatanController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Kegiatan;
use app\models\KegiatanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\UploadForm;
use frontend\models\NewUser;
/**
 * KegiatanController implements the CRUD actions for Kegiatan model.
 */
class KegiatanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kegiatan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Kegiatan::find();
        $searchModel = new KegiatanSearch();
        $searchModel->id_mhs = Yii::$app->user->id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = ['pageSize' => 5];
        $kegiatan = $query->one();
        $queryParams = Yii::$app->request->queryParams;
        if ( isset($queryParams['Kegiatan']['id_mhs']) ) {
            $queryParams['Kegiatan']['id_mhs'] = Yii::$app->user->id;
        }
        $dataProvider = $searchModel->search($queryParams);

        if (Yii::$app->user->isGuest) {
            $this->redirect(Yii::$app->urlManager->createUrl(['site/login']));
        }else{
          return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'kegiatan' => $kegiatan,
        ]);  
      }
  }

    /**
     * Displays a single Kegiatan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Kegiatan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Kegiatan();
        if ($model->load(Yii::$app->request->post())){
          $model->id_mhs = Yii::$app->user->id;
          $model->upload_proposal = "Initial";
          $model->save();
          $id_kegiatan = $model->id_kegiatan;
          $file = UploadedFile::getInstance($model, 'upload_proposal');
          $fileName = $file->baseName . '.' . $file->getExtension();
          $file->saveAs(Yii::getAlias('@frontend') . '/web/Kegiatan Mahasiswa/' . $fileName);
          $model->upload_proposal = $fileName;
          $model->save();

          return $this->redirect(['index', 'id' => $model->id_kegiatan]);
      }else{
        return $this->render('create', [
            'model' => $model,
        ]);
    }
}

 //Action Download
public function actionDownload($id) 
{ 
    $download = Kegiatan::findOne($id); 
    $path=Yii::getAlias('@frontend') . '/web/Kegiatan Mahasiswa/' . $download->upload_proposal;

    if (file_exists($path)) {
        return Yii::$app->response->sendFile($path);
    }
}

    /**
     * Updates an existing Kegiatan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())){
            $model->id_mhs = Yii::$app->user->id;
            $id_kegiatan = $model->id_kegiatan;
            $file = UploadedFile::getInstance($model, 'upload_proposal');
            $fileName = $file->baseName . '.' . $file->getExtension();
            $file->saveAs(Yii::getAlias('@frontend') . '/web/Kegiatan Mahasiswa/' . $fileName);
            $model->upload_proposal = $fileName;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id_kegiatan]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionPdf($id) {
        $model = Kegiatan::findOne($id);

    // This will need to be the path relative to the root of your app.
        $filePath = '/web/Kegiatan Mahasiswa/';
    // Might need to change '@app' for another alias
        $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_proposal);


        return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);


    }


    /**
     * Deletes an existing Kegiatan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Kegiatan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kegiatan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kegiatan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionViewFile($fileName){
        $file = Yii::getAlias('@frontend' . '/web/Kegiatan Mahasiswa/' . $fileName);
        return Yii::$app->response->sendFile($file, NULL, ['inline' => TRUE]);
    }
}

frontend/views/kegiatan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Kegiatan */
/* @var $form yii\widgets\ActiveForm */
$asset = frontend\assets\AppAsset::register($this);
$baseUrl = $asset->baseUrl;
?>

<div class="kegiatan-form">

	<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

	<div class="row">
		<div class="col-md-8 col-sm-8">
			<?= $form->field($model, 'jenis_kegiatan')->textInput(['maxlength' => true]) ?>
		</div>
	</div>

	<?= $form->field($model, 'upload_proposal')->fileInput() ?>

	<div class="form-group">
		<?= Html::submitButton($model->isNewRecord ? 'Simpan' : 'Selesai', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

		<?= Html::a('Batal', ['index'], ['class' => 'btn btn-danger']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

frontend/views/kegiatan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Beasiswa */

?>
<div class="kegiatan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_kegiatan') ?>

    <?= $form->field($model, 'id_mhs') ?>

    <?= $form->field($model, 'jenis_kegiatan') ?>

    <?= $form->field($model, 'upload_proposal') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/kegiatan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Kegiatan */


$this->title = 'Request Kegiatan';
$this->params['breadcrumbs'][] = ['label' => 'Kegiatan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kegiatan-create">
	
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/kegiatan/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use common\components\ToolsColumn;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KegiatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Kegiatan';
$this->params['breadcrumbs'][] = $this->title;
$uiHelper=\Yii::$app->uiHelper;
?>
<div class="kegiatan-index">

  <?= $uiHelper->renderContentHeader($this->title);?>
  <?php

  $toolbarItemMenu =  
  "<a href='".Url::to(['create'])."' class='btn btn-success'><i class='fa fa-book'></i><span class='toolbar-label'>Request Kegiatan</span></a>
  "
  ;



  ?>



  <?=Yii::$app->uiHelper->renderToolbar([
    'pull-left' => true,
    'groupTemplate' => ['groupStatusExpired'],
    'groups' => [
      'groupStatusExpired' => [
        'template' => ['filterStatus'],
        'buttons' => [
          'filterStatus' => $toolbarItemMenu,
        ]
      ],
    ],
  ]) ?>


  <?= GridView::widget([
    'dataProvider' => $dataProvider,
<<<<<<< frontend/views/kegiatan/index.php
    // 'filterModel' => $searchModel,
=======
>>>>>>> frontend/views/kegiatan/index.php
    'columns' => [
      ['class' => 'yii\grid\SerialColumn'],
      'jenis_kegiatan',
      ['attribute' => 'upload_proposal',
      'label' => 'Proposal Kegiatan',
      'format' => 'html',
      'value' => 
      function($model){
        return Html::a($model->upload_proposal, ['kegiatan/download', 'id'=> $model->id_kegiatan]);
      }
    ],
    ['attribute' => 'status_request_id',
    'label' => 'Status Request',
    'value' => function($model){
      if(is_null($model->statusRequest['name'])){
        return '-';
      }else{
        return $model->statusRequest['name'];
      }
    }
  ],

  ['class' => 'common\components\ToolsColumn',
  'template' => '{view} {edit}',
  'header' => 'Aksi',
  'buttons' => [
    'view' => function ($url, $model){
      return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
    },
    'edit' => function ($url, $model){
      if ($model->status_request_id == 1 || $model->status_request_id == 2) {
        return "";
      }else{
        return ToolsColumn::renderCustomButton($url, $model, 'Edit', 'fa fa-times');
      }
    },
  ],
  'urlCreator' => function ($action, $model, $key, $index){
    if ($action === 'view') {
      return Url::toRoute(['pdf', 'id' => $key]);
    }else if ($action === 'edit') {
      return Url::toRoute(['update', 'id' => $key]);
    }

  }
],

],


]); ?>


</div>

frontend/views/kegiatan/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Kegiatan */

$this->title = 'Update Data Kegiatan';
$this->params['breadcrumbs'][] = ['label' => 'Kegiatan', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="kegiatan-update">
	
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>


</div>

frontend/views/kegiatan/view-pdf.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Kegiatan */

$this->title = 'Data Kegiatan';



\yii\web\YiiAsset::register($this);
?>
<div class="kegiatan-view">

	


	<?= DetailView::widget([
		'model' => $model,
		'attributes' => [
			'jenis_kegiatan',
			['attribute' => 'upload_proposal',
			'label' => 'Proposal Kegiatan',
			'format' => 'html',
			'value' => 
			function($model){
				return Html::a($model->upload_proposal, ['kegiatan/download', 'id'=> $model->id_kegiatan]);
			}
		],
		['label' => 'Status Request', 'value' => $model->statusRequest->name],
	],



]) ?>



	<?= Html::a('Lihat Pdf ', [
    'pdf',
    'id' => $model->upload_proposal,
], [
    'class' => 'btn btn-primary',
    'target' => '_blank',
]); ?>

</div>

frontend/views/kegiatan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Kegiatan */

$this->title = 'Data Kegiatan';
$this->params['breadcrumbs'][] = ['label' => ' Kegiatan', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;


\yii\web\YiiAsset::register($this);
?>
<div class="kegiatan-view">

	<h1><?= Html::encode($this->title) ?></h1>


	<?= DetailView::widget([
		'model' => $model,
		'attributes' => [
			'jenis_kegiatan',
			['attribute' => 'upload_proposal',
			'label' => 'Proposal Kegiatan',
			'format' => 'html',
			'value' => 
			function($model){
				return Html::a($model->upload_proposal, ['kegiatan/download', 'id'=> $model->id_kegiatan]);
			}
		],
		['label' => 'Status Request', 'value' => $model->statusRequest->name],



		
	],



]) ?>
<?php 

echo Html::a('<i class="fa far fa-hand-point-up"></i> Privacy Statement', ['/view-privacy'], [
    'class'=>'btn btn-danger', 
    'target'=>'_blank', 
    'data-toggle'=>'tooltip', 
    'title'=>'Will open the generated PDF file in a new window'
]);
	
 ?>
	

</div>