backend/models/LpjKegiatan.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "lpj_kegiatan".
 *
 * @property int $id_LpjKegiatan
 * @property int $id_mhs
 * @property string $jenis_kegiatan
 * @property string $file_lpj
 * @property int $status_request_id
 */
class LpjKegiatan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'lpj_kegiatan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_mhs', 'jenis_kegiatan','file_lpj', 'status_request_id'], 'required'],
            [['id_mhs', 'status_request_id'], 'integer'],
            [['jenis_kegiatan'], 'string', 'max' => 50],
            [['file_lpj'], 'file', 'skipOnEmpty' => TRUE,'extensions'=>'pdf']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_LpjKegiatan' => 'Id Lpj Kegiatan',
            'id_mhs' => 'Id Mhs',
            'jenis_kegiatan' => 'Jenis Kegiatan',
            'file_lpj' => 'LPJ Kegiatan',
        ];
    }

       public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_mhs' => 'id_mhs']);
    }
}

frontend/models/LpjKegiatan.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "lpj_kegiatan".
 *
 * @property int $id_LpjKegiatan
 * @property int $id_mhs
 * @property string $jenis_kegiatan
 * @property string $file_lpj
 */
class LpjKegiatan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'lpj_kegiatan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['jenis_kegiatan', 'file_lpj'], 'required'],
            [['jenis_kegiatan'], 'safe'],
            [['file_lpj'], 'file', 'skipOnEmpty' => true, 'extensions'=>'pdf'],
            [['jenis_kegiatan'], 'string', 'max' => 50],
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_LpjKegiatan' => 'Id Lpj Kegiatan',
            'id_mhs' => 'Id Mhs',
            'jenis_kegiatan' => 'Jenis Kegiatan',
            'file_lpj' => 'File LPJ',
        ];
    }

    public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }


    public function getId()
    {
        return $this->hasOne(Id::className(), ['id_mhs' => 'id_mhs']);
    }

}

backend/controllers/LpjKegiatanController.php
<?php
namespace backend\controllers;

use Yii;
use backend\models\LpjKegiatan;
use backend\models\LpjKegiatanSearch;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\Notifikasi;

/**
 * LpjKegiatanController implements the CRUD actions for LpjKegiatan model.
 */
class LpjKegiatanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
      return [
        'access' => [
          'class' => AccessControl::className(),
          'rules'=> [
            [
              'actions' => ['login', 'error'],
              'allow' => true,
            ],
            [
              'actions' => ['logout', 'index'],
              'allow' => true,
              'roles' => ['@'],
            ],
            [
              'allow' => true,
              'roles' => ['@'],
            ],
          ],
        ],
        'verbs' => [
          'class' => VerbFilter::className(),
          'actions' => [
            'logout' => ['post'],
          ],
        ],
      ];
    }

    public function actions(){
      return [
        'error' => [
          'class' => 'yii\web\ErrorAction',
        ],
      ];
    }

    /**
     * Lists all LpjKegiatan models.
     * @return mixed
     */
    public function actionIndex()
    {
      $searchModel = new LpjKegiatanSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      $dataProvider->pagination = ['pageSize' => 5];
      return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
      ]);
    }


    public function actionApprove($id)
    {
      $model = LpjKegiatan::find()->where(['id_LpjKegiatan' => $id])->one();
      $notif = new Notifikasi();
      $notif->id_mhs = $model->id_mhs;
      $notif->desc = "LPJ Kegiatan Diterima";
      $model->status_request_id=1;
      $searchModel = new LpjKegiatanSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      if($model->save() && $notif->save(false)){

        return $this->render('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
        ]);
        
      }
    }

       public function actionPdf($id) {
    $model = LpjKegiatan::findOne($id);
        
    

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/LPJ Kegiatan/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->file_lpj);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

        
}


    public function actionReject($id)
    {
      $model = LpjKegiatan::find()->where(['id_LpjKegiatan' => $id])->one();
      $notif = new Notifikasi();
      $notif->id_mhs = $model->id_mhs;
      $notif->desc = "LPJ Kegiatan Ditolak";
      $model->status_request_id=2;
      $searchModel = new LpjKegiatanSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      if($model->save()){
    //disini buat savenya
       if ($notif->save(false)) {
        return $this->render('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
        ]);
      }
      
    }
  }

     //Action Download
  public function actionDownload($id) 
  { 
    $download = LpjKegiatan::findOne($id); 
    $path=Yii::getAlias('@frontend') . '/web/LPJ Kegiatan/' . $download->file_lpj;
    if (file_exists($path)) {
      return Yii::$app->response->sendFile($path);
    }
  }

  public function actionPdf($id) {
    $model = LpjKegiatan::findOne($id);

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/LPJ Kegiatan /';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->file_lpj);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

  }

    /**
     * Deletes an existing LpjKompetisi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
      $this->findModel($id)->delete();

      return $this->redirect(['index']);
    }



    /**
     * Displays a single LpjKegiatan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
      return $this->render('view', [
        'model' => $this->findModel($id),
      ]);
    }

    /**
     * Creates a new LpjKegiatan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
      $model=new LpjKegiatan;
      if(isset($_POST['NamaModel']))
      {
        $model->attributes=$_POST['LpjKegiatan'];
        $model->status_request_id=0;
        if($model->save())
          $this->redirect(array('view','id'=>$model->id));
      }
      $this->render('create',array(
        'model'=>$model,
      ));
    }



    /**
     * Updates an existing LpjKegiatan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdates($id)
    {
      $model=$this->loadModel($id);
      $model->status=1;
      if($model->save())
        $this->redirect(array('view','id'=>$model->id));

      $this->render('update',array(
        'model'=>$model,
      ));
    }
    protected function findModel($id)
    {
      if (($model = LpjKegiatan::findOne($id)) !== null) {
        return $model;
      } else {
        throw new NotFoundHttpException('The requested page does not exist.');
      }
    }
 /**
     * Login action.
     *
     * @return string
     */
 public function actionLogin()
 {
  if (!Yii::$app->user->isGuest) {
    return $this->goHome();
  }

  $model = new LoginForm();
  if ($model->load(Yii::$app->request->post()) && $model->login()) {
    return $this->goBack();
  } else {
    $model->password = '';

    return $this->render('login', [
      'model' => $model,
    ]);
  }
}


    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
      Yii::$app->user->logout();

      return $this->goHome();
    }
  }

frontend/controllers/LPJKegiatanController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\LPJKegiatan;
use app\models\LPJKegiatanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\UploadForm;
use frontend\models\NewUser;

/**
 * LPJKegiatanController implements the CRUD actions for LPJKegiatan model.
 */
class LPJKegiatanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all LPJKegiatan models.
     * @return mixed
     */
    public function actionIndex()
    {

        $query = LPJKegiatan::find();
        $searchModel = new LPJKegiatanSearch();
        $searchModel->id_mhs = Yii::$app->user->id;
        
        $lpj_kompetisi = $query->all();
        $queryParams = Yii::$app->request->queryParams;
        if ( isset($queryParams['LPJKegiatan']['id_mhs']) ) {
            $queryParams['LPJKegiatan']['id_mhs'] = Yii::$app->user->id;
        }
        $dataProvider = $searchModel->search($queryParams);

        if (Yii::$app->user->isGuest) {
            $this->redirect(Yii::$app->urlManager->createUrl(['site/login']));
        }else{
          return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'lpj_kompetisi' => $lpj_kompetisi,
        ]);  
      }
  }

    /**
     * Displays a single LPJKegiatan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionPdf($id) {
    $model = LPJKegiatan::findOne($id);
        
    

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/LPJ Kegiatan/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->file_lpj);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

        
}
    /**
     * Creates a new LPJKegiatan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new LpjKegiatan();
        if ($model->load(Yii::$app->request->post())) {
            $model->id_mhs = Yii::$app->user->id;
            $model->file_lpj = "Initial";
            $model->save();

            $id_LpjKegiatan = $model->id_LpjKegiatan;
            $file = UploadedFile::getInstance($model, 'file_lpj');
            $fileName = $file->baseName . '.' . $file->getExtension();
            $file->saveAs(Yii::getAlias('@frontend') . '/web/LPJ Kegiatan/' . $fileName);
            $model
            ->file_lpj = $fileName;
            $model->save();

            return $this->redirect(['index', 'id' => $model->id_LpjKegiatan]);
        }else{
            return $this->render('create', [
                'model' => $model,

            ]);
        }
    }

     //Action Download
    public function actionDownload($id) 
    { 
        $download = LpjKegiatan::findOne($id); 
        $path=Yii::getAlias('@frontend') . '/web/LPJ Kegiatan/' . $download->file_lpj;

        if (file_exists($path)) {
            return Yii::$app->response->sendFile($path);
        }
    }

    /**
     * Updates an existing LPJKegiatan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $id_LpjKegiatan = $model->id_LpjKegiatan;
            $file = UploadedFile::getInstance($model, 'file_lpj');
            $fileName = $file->baseName . '.' .$file->getExtension();
            $file->saveAs(Yii::getAlias('@frontend') . '/web/LPJ Kegiatan/' . $fileName);
            $model->file_lpj = $fileName;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id_LpjKegiatan]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionPdf($id) {
        $model = LPJKegiatan::findOne($id);

    // This will need to be the path relative to the root of your app.
        $filePath = '/web/LPJ Kegiatan/';
    // Might need to change '@app' for another alias
        $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->file_lpj);


        return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);


    }

    /**
     * Deletes an existing LPJKegiatan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the LPJKegiatan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return LPJKegiatan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = LpjKegiatan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionViewFile($fileName){
        $file = Yii::getAlias('@frontend' . '/web/LPJ Kegiatan' . $fileName);
        return Yii::$app->response->sendFile($file, NULL, ['inline' => TRUE]);
    }
}

backend/views/lpj-kegiatan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LpjKegiatan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lpj-kegiatan-form">
	<?php $form = ActiveForm::begin(); ?>
	<?= $form->field($model, 'id_LpjKegiatan')->textInput()?>
	<?= $form->field($model, 'jenis_kegiatan')->textInput(['maxlength' => true]) ?>

	<<?= $form->field($model, 'file_lpj')->fileInput() ?>


	<div class="form-group">
		<?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

backend/views/lpj-kegiatan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
use backend\models\NewUser;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\LpjKegiatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'LPJ Kegiatan');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lpj-kegiatan-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            
            'jenis_kegiatan',
            ['attribute' => 'file_lpj',
            'label' => 'LPJ Kegiatan',
            'format' => 'html',
            'value' => 
            function($model){
                return Html::a($model->file_lpj, ['lpj-kegiatan/download', 'id'=> $model->id_LpjKegiatan]);
            }
        ],
        ['attribute' => 'status_request_id',
        'label' => 'Status Request',
        'value' => function($model){
            if(is_null($model->statusRequest['name'])){
                return '-';
            }else{
                return $model->statusRequest['name'];
            }
        }
    ],

    ['class' => 'common\components\ToolsColumn',
    'template' => '{view} {approve} {reject}',
    'header' => 'Aksi',
    'buttons' => [
        'view' => function ($url, $model){
            return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
        },
        'reject' => function ($url, $model){
            if ($model->status_request_id == 1 || $model->status_request_id == 2 ) {
                return "";
            }else{
                return ToolsColumn::renderCustomButton($url, $model, 'Reject', 'fa fa-times');
            }
        },
        'approve' => function ($url, $model){
            if ($model->status_request_id == 1 || $model->status_request_id == 2 ) {
                return "";
            }else{
                return ToolsColumn::renderCustomButton($url, $model, 'Approve', 'fa fa-check');
            }
        },
    ],
],
],

]); ?>

</div>

backend/views/lpj-kegiatan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
use backend\models\NewUser;

/* @var $this yii\web\View */
/* @var $model backend\modules\kmhs\models\KegiatanMahasiswa */
$this->title = 'Data LPJ Kegiatan';
?>
<div class="lpj-kegiatan-view">
  <h1><?= Html::encode($this->title) ?></h1>
  <?= DetailView::widget([
    'model' => $model,
    'attributes' => [

     ['label'=>'Nama Mahasiswa',
     'value' => function ($data) {
      return NewUser::findOne(['id_mhs'=>$data->id_mhs])->username;
    },
  ],
  'jenis_kegiatan',
  ['attribute' => 'file_lpj',
  'label' => 'LPJ Kegiatan',
  'format' => 'html',
  'value' => 
  function($model){
    return Html::a($model->file_lpj, ['lpj-kegiatan/download', 'id'=> $model->id_LpjKegiatan]);
  }
],
['label' => 'Status Request', 'value' => $model->statusRequest->name],
],
]) ?>
  <?= Html::a('Lihat Pdf', [
    'pdf',
    'id' => $model->id_LpjKegiatan,
  ], [
    'class' => 'btn btn-primary',
    'target' => '_blank',
  ]); ?>
</div>