backend/models/Prestasi.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "prestasi".
 *
 * @property int $id_prestasi
 * @property int $id_mhs
 * @property string $jenis_prestasi
 * @property string $tgl_awal_kegiatan
 * @property string $tgl_akhir_kegiatan
 * @property string $upload_file
 * @property string $keterangan
 * @property int $status_request_id
 *
 * @property StatusRequest $statusRequest
 */
class Prestasi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'prestasi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_mhs', 'jenis_prestasi', 'tgl_awal_kegiatan', 'tgl_akhir_kegiatan', 'upload_file', 'keterangan', 'status_request_id'], 'required'],
            [['id_mhs', 'status_request_id'], 'integer'],
            [['tgl_awal_kegiatan', 'tgl_akhir_kegiatan'], 'safe'],
            [['jenis_prestasi', 'upload_file', 'keterangan'], 'string', 'max' => 255],
            [['status_request_id'], 'exist', 'skipOnError' => true, 'targetClass' => StatusRequest::className(), 'targetAttribute' => ['status_request_id' => 'status_request_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_prestasi' => 'Id Prestasi',
            'id_mhs' => 'Id Mhs',
            'jenis_prestasi' => 'Jenis Prestasi',
            'tgl_awal_kegiatan' => 'Tgl Awal Kegiatan',
            'tgl_akhir_kegiatan' => 'Tgl Akhir Kegiatan',
            'upload_file' => 'Upload File',
            'keterangan' => 'Lokasi',
            'status_request_id' => 'Status Request ID',
        ];
    }

    /**
     * Gets query for [[StatusRequest]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_mhs' => 'id_mhs']);
    }
}

frontend/models/Prestasi.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "prestasi".
 *
 * @property int $id_prestasi
 * @property string $jenis_prestasi
 * @property string $tgl_awal_kegiatan
 * @property string $tgl_akhir_kegiatan
 * @property string $upload_file
 * @property string $keterangan
 */
class Prestasi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'prestasi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['jenis_prestasi',  'tgl_awal_kegiatan', 'tgl_akhir_kegiatan', 'upload_file', 'keterangan'], 'required'],
            [[ 'tgl_awal_kegiatan', 'tgl_akhir_kegiatan'], 'safe'],
            [['jenis_prestasi',  'keterangan'], 'string', 'max' => 255],
            
            [['upload_file'], 'file','skipOnEmpty'=>TRUE,'extensions'=>'pdf']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'jenis_prestasi' => 'Jenis Prestasi',
            'id_mhs' => 'Id Mhs',
            'tgl_awal_kegiatan' => 'Tgl Awal Kegiatan',
            'tgl_akhir_kegiatan' => 'Tgl Akhir Kegiatan',
            'upload_file' => 'Upload File',
            'keterangan' => 'Lokasi',
            
        ];
    }
    public function getStatusRequest()
    {
        return $this->hasOne(StatusRequest::className(), ['status_request_id' => 'status_request_id']);
    }
    public function getId()
    {
        return $this->hasOne(Id::className(), ['id_mhs' => 'id_mhs']);
    }
}

backend/controllers/PrestasiController.php
<?php
namespace backend\controllers;

use Yii;
use backend\models\Prestasi;
use backend\models\PrestasiSearch;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\Notifikasi;



class PrestasiController extends Controller{

    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules'=> [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions(){
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex(){
        $searchModel = new PrestasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = ['pageSize' => 5];
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' =>$dataProvider,
        ]);
    }

    public function actionApprove($id)
    {
        $model = Prestasi::find()->where(['id_prestasi' => $id])->one();
        $notif = new Notifikasi();
        $notif->id_mhs = $model->id_mhs;
        $notif->desc = "Dokumentasi Prestasi Diterima";
        $model->status_request_id=1;
        $searchModel = new PrestasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if($model->save() && $notif->save(false)){

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
            
        }
    }

    public function actionPdf($id) {
    $model = Prestasi::findOne($id);
        
    

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/Prestasi Mahasiswa/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_file);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

        
}


    public function actionReject($id)
    {
        $model = Prestasi::find()->where(['id_prestasi' => $id])->one();
        $notif = new Notifikasi();
        $notif->id_mhs = $model->id_mhs;
        $notif->desc = "Dokumentasi Prestasi Ditolak";
        $model->status_request_id=2;
        $searchModel = new LpjKegiatanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if($model->save()){
    //disini buat savenya
         if ($notif->save(false)) {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        
    }

public function actionCreate()
{
    $model=new Prestasi;
    if(isset($_POST['NamaModel']))
    {
        $model->attributes=$_POST['Prestasi'];
        $model->status_request_id=0;
        if($model->save())
            $this->redirect(array('view','id'=>$model->id));
    }
    $this->render('create',array(
        'model'=>$model,
    ));
}

public function actionDownload($id) 
{ 
    $download = Prestasi::findOne($id); 
    $path=Yii::getAlias('@frontend') . '/web/Prestasi Mahasiswa/' . $download->upload_file;
    if (file_exists($path)) {
        return Yii::$app->response->sendFile($path);
    }
}
public function actionUpdates($id)
{
    $model=$this->loadModel($id);
    $model->status=1;
    if($model->save())
        $this->redirect(array('view','id'=>$model->id));

    $this->render('update',array(
        'model'=>$model,
    ));
}

public function actionPdf($id) {
    $model = Prestasi::findOne($id);

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/Prestasi Mahasiswa /';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_file);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);


}

protected function findModel($id)
{
    if (($model = Prestasi::findOne($id)) !== null) {
        return $model;
    } else {
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

public function actionView($id)
{
    return $this->render('view', [
        'model' => $this->findModel($id),
    ]);
}

public function actionExcel()
{
    $searchModel = new PrestasiSearch();
    $dataProvider = $searchModel->searchExcel(Yii::$app->request->queryParams);
    return $this->render('excel', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
    ]);
}
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/PrestasiController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Prestasi;
use app\models\PrestasiSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use app\models\UploadForm;
use app\models\NewUser;

/**
 * PrestasiController implements the CRUD actions for Prestasi model.
 */
class PrestasiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Prestasi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Prestasi::find();
        $searchModel = new PrestasiSearch();
        $searchModel->id_mhs = Yii::$app->user->id;
        
        $prestasi_ = $query->all();
        $queryParams = Yii::$app->request->queryParams;
        if ( isset($queryParams['Prestasi']['id_mhs']) ) {
            $queryParams['Prestasi']['id_mhs'] = Yii::$app->user->id;
        }
        $dataProvider = $searchModel->search($queryParams);

        if (Yii::$app->user->isGuest) {
            $this->redirect(Yii::$app->urlManager->createUrl(['site/login']));
        }else{
          return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'prestasi_' => $prestasi_,
        ]);  
      }

  }

    /**
     * Displays a single Prestasi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionPdf($id) {
    $model = Prestasi::findOne($id);
        
    

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/Prestasi Mahasiswa/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_file);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);

        
}

    public function actionView_Tolak($id)
    {
        return $this->render('view_tolak', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionView_Menunggu($id)
    {
        return $this->render('view_menunggu', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionUpdate1($id)
    {
        return $this->render('update', [
            'model' => $this->findModel($id),
        ]);
    }



    /**
     * Creates a new Prestasi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Prestasi();
        if ($model->load(Yii::$app->request->post())) {
            $model->id_mhs = Yii::$app->user->id;
            $model->upload_file = "Initial";
            $model->save();
            $id_prestasi = $model->id_prestasi;
            $file = UploadedFile::getInstance($model, 'upload_file');
            $fileName = $file->baseName . '.' . $file->getExtension();
            $file->saveAs(Yii::getAlias('@frontend') . '/web/Prestasi Mahasiswa/' . $fileName);
            $model->upload_file = $fileName;
            $model->save();
            
            return $this->redirect(['index', 'id' => $model->id_prestasi]);
        }else{
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Prestasi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $id_prestasi = $model->id_prestasi;
            $file = UploadedFile::getInstance($model, 'upload_file');
            $fileName = 'prestasi_' . $id_prestasi . '.' .$file->getExtension();
            $file->saveAs(Yii::getAlias('@frontend') . '/web/Prestasi Mahasiswa/' . $fileName);
            $model->upload_file = $fileName;
            $model->save();
            return $this->redirect(['view', 'id' => $model->id_prestasi]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Prestasi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        
        return $this->redirect(['index']);
    }

    public function actionDownload($id) 
    { 
      $download = Prestasi::findOne($id); 
      $path=Yii::getAlias('@frontend') . '/web/Prestasi Mahasiswa/' . $download->upload_file;
      
      if (file_exists($path)) {
          return Yii::$app->response->sendFile($path);
      }
  }


  public function actionPdf($id) {
    $model = Prestasi::findOne($id);

    // This will need to be the path relative to the root of your app.
    $filePath = '/web/Prestasi Mahasiswa/';
    // Might need to change '@app' for another alias
    $completePath = Yii::getAlias('@frontend'.$filePath.'/'.$model->upload_file);

    
    return Yii::$app->response->sendFile($completePath, $filePath, ['inline'=>true]);


}

    /**
     * Finds the Prestasi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Prestasi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Prestasi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionViewFile($fileName){
        $file = Yii::getAlias('@frontend' . '/web/Prestasi Mahasiswa/' . $fileName);
        return Yii::$app->response->sendFile($file, NULL, ['inline' => TRUE]);
    }
}

backend/views/prestasi/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiverForm;

?>
<div class="prestasi-form">

<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'id_prestasi')->textInput()?>
<?= $form->field($model, 'jenis_prestas')->textInput(['maxlength' => true]) ?>

    <<?= $form->field($model, 'upload_proposal')->fileInput() ?>


    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/prestasi/excel.php
<?php
use backend\models\NewUser;

\backend\assets\web\php\ExcelGrid::Widget([
	'dataProvider'=> $dataProvider,
	'filterModel' => $searchModel,
	'filename'	  => 'Prestasi',
	'properties'  => [

	],
	'columns'	 => [
		['class' =>  'yii\grid\SerialColumn'],
		['attribute' => 'firstname',
		'label' => 'Nama Mahasiswa',
		'value' => function ($data) {
			return NewUser::findOne(['id_mhs'=>$data->id_mhs])->username;
		},
	],

	'jenis_prestasi',
	'tgl_awal_kegiatan',
	'tgl_akhir_kegiatan',
	'keterangan',

	['attribute' => 'status_request_id',
	'label' => 'Status Request',
	'value' => function($model){
		if(is_null($model->statusRequest['name'])){
			return '-';
		}else{
			return $model->statusRequest['name'];
		}
	}
],
]
])
?>

backend/views/prestasi/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\KegiatanSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Dokumentasi Prestasi');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prestasi-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <p> <?= Html::a('Export ke Excel', ['excel'], ['class' => 'btn btn-primary']) ?> 
</p>
<<<<<<< backend/views/prestasi/index.php
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    
    'columns' => [
       
        'jenis_prestasi',
        'tgl_awal_kegiatan',
        'tgl_akhir_kegiatan',
        
=======

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'jenis_prestasi',
            'tgl_awal_kegiatan',
            'tgl_akhir_kegiatan',
>>>>>>> backend/views/prestasi/index.php
            // 'keterangan',
        //     ['attribute' => 'upload_file',
        //     'label' => 'File Prestasi',
        //     'format' => 'html',
        //     'value' => 
        //     function($model){
        //         return Html::a($model->upload_file, ['prestasi/download', 'id'=> $model->id_prestasi]);
        //     }
        // ],
        ['attribute' => 'status_request_id',
        'label' => 'Status Request',
        'value' => function($model){
            if(is_null($model->statusRequest['name'])){
                return '-';
            }else{
                return $model->statusRequest['name'];
            }
        }
    ],

    ['class' => 'common\components\ToolsColumn',
    'template' => '{view} {approve} {reject}',
    'header' => 'Aksi',
    'buttons' => [
        'view' => function ($url, $model){
            return ToolsColumn::renderCustomButton($url, $model, 'View Detail', 'fa fa-eye');
        },
        'reject' => function ($url, $model){
            if ($model->status_request_id == 1 || $model->status_request_id == 2 ) {
                return "";
            }else{
                return ToolsColumn::renderCustomButton($url, $model, 'Reject', 'fa fa-times');
            }
        },
        'approve' => function ($url, $model){
            if ($model->status_request_id == 1 || $model->status_request_id == 2 ) {
                return "";
            }else{
                return ToolsColumn::renderCustomButton($url, $model, 'Approve', 'fa fa-check');
            }
        },

        'urlCreator' => function ($action, $model, $key, $index){
            if ($action === 'view') {
              return Url::toRoute(['view', 'id' => $key]);
          }else if ($action === 'edit') {
              return Url::toRoute(['update', 'id' => $key]);
          }

      }


  ],
],
],

]); ?>

</div>

backend/views/prestasi/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use common\components\ToolsColumn;
use common\helpers\LinkHelper;
use backend\models\NewUser;

/* @var $this yii\web\View */
/* @var $model backend\modules\kmhs\models\KegiatanMahasiswa */
$this->title = 'Data Prestasi Mahasiswa';
?>
<div class="prestasi-view">
  <h1><?= Html::encode($this->title) ?></h1>
  <?= DetailView::widget([
    'model' => $model,
    'attributes' => [

      ['label'=>'Nama Mahasiswa',
      'value' => function ($data) {
        return NewUser::findOne(['id_mhs'=>$data->id_mhs])->username;
      },
    ],

    'jenis_prestasi',
    'tgl_awal_kegiatan',
    'tgl_akhir_kegiatan',
    'keterangan',
    ['attribute' => 'upload_file',
    'label' => 'File Prestasi',
    'format' => 'html',
    'value' => 
    function($model){
      return Html::a($model->upload_file, ['prestasi/download', 'id'=> $model->id_prestasi]);
    }
  ],
  ['label' => 'Status Request', 'value' => $model->statusRequest->name],
],
]) ?>

  <?= Html::a('Lihat Pdf', [
    'pdf',
    'id' => $model->id_prestasi,
  ], [
    'class' => 'btn btn-primary',
    'target' => '_blank',
  ]); ?>

</div>